Dev
Porestoranam/Films-Review-Python pull request #1
Opened 2019-05-20 21:26 UTC by Porestoranam

first pull

2019-05-21 18:07 UTC, WokinShopash requested changes

2019-05-21 18:07 UTC, WokinShopash commented on README.md
> +По другому не работает, пока что не очень понял как нужно принимать аргумент от клиента на базу данных,
Клиент никак и не должен принимать аргумент про базу данных, все так

2019-05-21 18:07 UTC, WokinShopash commented on tools.py
> +genres_valuates[('action', 'action')] = 1
Вот эти константы надо унести в отдельный файл.

2019-05-21 18:07 UTC, WokinShopash commented on tools.py
> +          "musicals", "science fiction", "war", "western"]
Отступы поехали

2019-05-21 18:07 UTC, WokinShopash commented on tools.py
> +    elif int(_mood) < 1 or int(_mood) > 10:
Можно использовать двойные неравенства:
`if not (1 <= int(_mood) <= 10)`

2019-05-21 18:07 UTC, WokinShopash commented on server.py
> +params = dict(dbname="postgres", user="postgres", password="8246", host="localhost")
Вот эти параметры надо настраивать через argparse или конфигурационный файл

2019-05-21 18:07 UTC, WokinShopash commented on requirements.txt
> +Django==2.2
Джанго тут зачем? Как и половина прочих requirements

2019-05-21 18:07 UTC, WokinShopash commented on server.py
> +    cur.execute('DROP TABLE IF EXISTS bd_films CASCADE')
При перезапуске сервера не надо дропать базу.
Наоборот, база нужна, чтобы перезапуске сервера данные не убивались!

2019-05-21 18:07 UTC, WokinShopash commented on client.py
> +        option = input()
Для устойчивости к пробелами лучше добавить strip()

2019-05-21 18:07 UTC, WokinShopash commented on client.py
> +        print("############################################")
Вот эти триллионы скобок можно через умножение строки на число. И наверх, в константы

2019-05-21 18:07 UTC, WokinShopash commented on server.py
> +        flask.abort(400)
Лучше все-таки добавлять какое-то сообщение, чтобы дать пользователю понять, что не так

2019-05-21 18:07 UTC, WokinShopash commented on server.py
> +    q = "SELECT mood, company, people, age, genres FROM user_session where nick = '{}'".format(cur_nick)
Никогда нельзя использовать format для подстановки значений, всякие SQL-инъекции и т.д.
Читай вот тут как надо делать: www.psycopg.org/psycopg/docs/usage.html#passing-parameters-to-sql-queries

2019-05-23 14:33 UTC, Porestoranam commented on tools.py
> +    elif int(_mood) < 1 or int(_mood) > 10:
Да

2020-03-11 16:57 UTC, merged